@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
'https://plantuml.com/activity-diagram-beta

start
:User uses addSched command;
if () then ([schedule details valid])
    :Look through user(s)'
    schedule in Storage;
    :add schedule to user(s)' schedule list;
else ([else])
endif
stop

@enduml
